#!/usr/bin/env bash
# init.sh — Environment bootstrap for Node.js/Next.js projects
# Generated by Ralph Loop initializer. Customize for your project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Ralph init.sh starting ==="
echo "Project: {{PROJECT_NAME}} | Stack: {{TECH_STACK}}"

# Install dependencies
echo "[1/4] Installing dependencies..."
npm install --silent 2>/dev/null || npm install

# Environment file
if [[ ! -f ".env.local" ]]; then
  echo "[2/4] Creating .env.local..."
  cp .env.example .env.local 2>/dev/null || cat > .env.local << 'EOF'
DATABASE_URL="{{DATABASE_URL}}"
NEXTAUTH_SECRET="ralph-dev-secret-$(date +%s)"
NEXTAUTH_URL="{{BASE_URL}}"
EOF
fi

# Database setup (Prisma)
if [[ -f "prisma/schema.prisma" ]]; then
  echo "[3/4] Running database setup..."
  npx prisma migrate dev --name init 2>/dev/null || \
  npx prisma db push --accept-data-loss 2>/dev/null || \
  echo "  Database up to date"
fi

# Start dev server
echo "[4/4] Starting dev server..."
pkill -f "next dev" 2>/dev/null || true
npm run dev &>/tmp/ralph-dev.log &
DEV_PID=$!

# Wait for health check
echo "  Waiting for server to be ready..."
MAX_WAIT=60
for i in $(seq 1 $MAX_WAIT); do
  if curl -s -o /dev/null -w "%{http_code}" {{BASE_URL}} 2>/dev/null | grep -qE "200|304"; then
    echo ""
    echo "=== READY (server: {{BASE_URL}}, PID: $DEV_PID) ==="
    exit 0
  fi
  sleep 1
done

echo ""
echo "ERROR: Server failed to start within ${MAX_WAIT}s"
echo "Last 20 lines of dev log:"
tail -20 /tmp/ralph-dev.log
exit 1
