#!/usr/bin/env bash
# init.sh — Environment bootstrap for Python/FastAPI projects
# Generated by Ralph Loop initializer. Customize for your project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Ralph init.sh starting ==="
echo "Project: {{PROJECT_NAME}} | Stack: {{TECH_STACK}}"

# Virtual environment
if [[ ! -d "venv" ]]; then
  echo "[1/4] Creating virtual environment..."
  python3 -m venv venv
fi
source venv/bin/activate

# Install dependencies
echo "[2/4] Installing dependencies..."
pip install -r requirements.txt -q 2>/dev/null || pip install -r requirements.txt

# Database setup
echo "[3/4] Running database setup..."
python3 -c "from app.db import init_db; init_db()" 2>/dev/null || \
python3 -c "from app.database import init_db; init_db()" 2>/dev/null || \
echo "  Database setup skipped (no init_db found)"

# Start server
echo "[4/4] Starting API server..."
pkill -f "uvicorn" 2>/dev/null || true
uvicorn app.main:app --reload --port {{PORT}} &>/tmp/ralph-api.log &
API_PID=$!

# Wait for health check
echo "  Waiting for server to be ready..."
MAX_WAIT=30
for i in $(seq 1 $MAX_WAIT); do
  if curl -s {{BASE_URL}}/health 2>/dev/null | grep -q "ok"; then
    echo ""
    echo "=== READY (API: {{BASE_URL}}, PID: $API_PID) ==="
    exit 0
  fi
  sleep 1
done

echo ""
echo "ERROR: API failed to start within ${MAX_WAIT}s"
echo "Last 20 lines of API log:"
tail -20 /tmp/ralph-api.log
exit 1
